spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_database
    username: root
    password: password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _HISTORY
            store_data_at_delete: true
  flyway:
    enabled: true

article:
  schema: https
  domain: SERVER_URL
  pagination:
    album: /api/albums?page=

---

spring:
  profiles: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

article:
  schema: http
  domain: SERVER_URL