CREATE TABLE ALBUM (
	ALBUM_KEY            bigint GENERATED ALWAYS AS IDENTITY  NOT NULL,
	ALBUM_ID             char(14)   NOT NULL,
	TITLE                varchar(150)   NOT NULL,
	DELETED              boolean  DEFAULT 0 NOT NULL,
	CREATE_UTC           timestamp  DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "Pk_ALBUM_KEY" PRIMARY KEY ( ALBUM_KEY ),
	CONSTRAINT IDX_ALBUM_UNIQUE_ALBUM_ID UNIQUE ( ALBUM_ID ) 
 );

CREATE INDEX IDX_ALBUM_TITLE ON ALBUM ( TITLE );

COMMENT ON TABLE ALBUM IS '앨범 정보 테이블';

CREATE TABLE ALB_LOCALE ( 
	LOCALE_KEY           bigint GENERATED ALWAYS AS IDENTITY  NOT NULL,
	ALBUM_KEY            bigint   NOT NULL,
	LOCALE_CODE          char(3)   NOT NULL,
	CREATE_UTC           timestamp  DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "Pk_ALB_LOCALE_LOCALE_KEY" PRIMARY KEY ( LOCALE_KEY ),
	CONSTRAINT IDX_ALB_LOCALE_UNIQUE_LOCALE UNIQUE ( ALBUM_KEY, LOCALE_CODE ) 
 );

COMMENT ON TABLE ALB_LOCALE IS '앨범 서비스 가능 지역 코드 정보 테이블';

CREATE TABLE PLAYLIST ( 
	PLAYLIST_KEY         bigint GENERATED ALWAYS AS IDENTITY  NOT NULL,
	PLAYLIST_ID          char(14)   NOT NULL,
	TITLE                varchar(150)   NOT NULL,
	CREATE_BY            char(14)   NOT NULL,
	CREATE_UTC           timestamp  DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "Pk_PLAYLIST_PLAYLIST_KEY" PRIMARY KEY ( PLAYLIST_KEY ),
	CONSTRAINT IDX_PLAYLIST_UNIQUE_PLAYLIST_ID UNIQUE ( PLAYLIST_ID ) 
 );

CREATE INDEX IDX_PLAYLIST_TITLE ON PLAYLIST ( TITLE );

CREATE INDEX IDX_PLAYLIST_CREATE_BY ON PLAYLIST ( CREATE_BY );

COMMENT ON TABLE PLAYLIST IS '사용자 플레이 리스트 정보 테이블';

CREATE TABLE SONG ( 
	SONG_KEY             bigint GENERATED ALWAYS AS IDENTITY  NOT NULL,
	SONG_ID              char(14)   NOT NULL,
	ALBUM_KEY            bigint   NOT NULL,
	TITLE                varchar(150)   NOT NULL,
	LENGTH               varchar   NOT NULL,
	TRACK_NO             tinyint   NOT NULL,
	DELETED              boolean  DEFAULT 0 NOT NULL,
	CREATE_UTC           timestamp  DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT PK_SONGS_SONG_KEY PRIMARY KEY ( SONG_KEY ),
	CONSTRAINT IDX_SONG_UNIQUE_SONG_ID UNIQUE ( SONG_ID ) 
 );

CREATE INDEX IDX_SONG_FK_ALBUM_KEY ON SONG ( ALBUM_KEY );

CREATE INDEX IDX_SONG_TITLE ON SONG ( TITLE );

COMMENT ON TABLE SONG IS '곡 정보 테이블';

CREATE TABLE PL_INVENTORY ( 
	INVENTORY_KEY        bigint GENERATED ALWAYS AS IDENTITY  NOT NULL,
	INVENTORY_ID         char(14)   NOT NULL,
	PLAYLIST_KEY         bigint   NOT NULL,
	SONG_KEY             bigint   NOT NULL,
	CREATE_UTC           timestamp  DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "Pk_PL_INVENTORY_INVENTORY_KEY" PRIMARY KEY ( INVENTORY_KEY ),
	CONSTRAINT IDX_PL_INVENTORY_UNIQUE_INVENTORY_ID UNIQUE ( INVENTORY_ID ) 
 );

COMMENT ON TABLE PL_INVENTORY IS '사용자 플레이리스트 수록곡 정보 테이블';

ALTER TABLE ALB_LOCALE ADD CONSTRAINT IDX_ALB_LOCALE_FK_ALBUM_KEY FOREIGN KEY ( ALBUM_KEY ) REFERENCES ALBUM( ALBUM_KEY );

ALTER TABLE PL_INVENTORY ADD CONSTRAINT IDX_PL_INVENTORY_FK_PLAYLIST_KEY FOREIGN KEY ( PLAYLIST_KEY ) REFERENCES PLAYLIST( PLAYLIST_KEY );

ALTER TABLE PL_INVENTORY ADD CONSTRAINT IDX_PL_INVENTORY_FK_SONG_KEY FOREIGN KEY ( SONG_KEY ) REFERENCES SONG( SONG_KEY );

ALTER TABLE SONG ADD CONSTRAINT IDX_SONG_FK_ALBUM_KEY FOREIGN KEY ( ALBUM_KEY ) REFERENCES ALBUM( ALBUM_KEY );

CREATE TABLE REVINFO ( 
	REV                  bigint GENERATED ALWAYS AS IDENTITY  NOT NULL,
	REVTSTMP             bigint   ,
	CONSTRAINT "pk_revinfo" PRIMARY KEY ( REV )
 );

CREATE TABLE PLAYLIST_HISTORY ( 
	PLAYLIST_KEY         bigint   NOT NULL,
	REV                  bigint   NOT NULL,
	REVTYPE              tinyint   ,
	PLAYLIST_ID          char(14)   NOT NULL,
	TITLE                varchar(150)   NOT NULL,
	CREATE_BY            char(14)   NOT NULL,
	CREATE_UTC           timestamp  DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "pk_playlist_history" PRIMARY KEY ( PLAYLIST_KEY, REV )
 );

CREATE INDEX IDX_PLAYLIST_AUD_FK_REV ON PLAYLIST_HISTORY ( REV );

CREATE TABLE PL_INVENTORY_HISTORY ( 
	INVENTORY_KEY        bigint   NOT NULL,
	REV                  bigint   NOT NULL,
	REVTYPE              tinyint   ,
	INVENTORY_ID         char(14)   NOT NULL,
	PLAYLIST_KEY         bigint   NOT NULL,
	SONG_KEY             bigint   NOT NULL,
	CREATE_UTC           timestamp  DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "pk_pl_inventory_history" PRIMARY KEY ( INVENTORY_KEY, REV )
 );

CREATE INDEX IDX_PL_INVENTORY_AUD_FK_REV ON PL_INVENTORY_HISTORY ( REV );

ALTER TABLE PLAYLIST_HISTORY ADD CONSTRAINT IDX_PLAYLIST_AUD_FK_REV FOREIGN KEY ( REV ) REFERENCES REVINFO( REV ) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PL_INVENTORY_HISTORY ADD CONSTRAINT IDX_PL_INVENTORY_AUD_FK_REV FOREIGN KEY ( REV ) REFERENCES REVINFO( REV ) ON DELETE RESTRICT ON UPDATE RESTRICT;
